### ISSUE TITLE
Error: milliseconds not a number

### ISSUE THREAD

**Issue by Coruna** [github-actions-up-and-running/pr-comment#7]
If I try to use your action I get the following error on runtime:

`Run github-actions-up-and-running/pr-comment@v1.0.0
  with:
    repo-token: ***
    message: Nice PR!
    myInput: default value if applicable
##[error]milliseconds not a number`

with my workflow.yml file:

` name: Comment

on: 
  pull_request:
    types: [opened, edited, reopened, labeled]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Nice PR!`

**Comment by miyajan** [comment]
@Coruna Sorry, I found that v1.0.0 doesn't work because I made a mistake when creating the tag.🙇‍♂️

I have created v1.0.1, please use it!
